### ISSUE TITLE
program not working on my Mac 2016 =)

### ISSUE THREAD

**Issue by d-arkhipenko** [mbasiuk/FAQ#7]

**Comment by mbasiuk** [comment]
could not reproduce;

**Comment by d-arkhipenko** [comment]
still not working!! fix this shit !!!

**Comment by mbasiuk** [comment]
try build for .net core https://www.microsoft.com/net/core#windowsvs2015

**Comment by KaBaJIeP** [comment]
i am a user, this not my problem - this is peace of shet not working !!!

**Comment by d-arkhipenko** [comment]
this is piece of shit still not working - fix it !!!
